#!/bin/bash

set -e

git am --abort || true
git checkout build || git checkout -b build
git reset --hard grub-2.06

git am ../patch/riscv-adjust-march-flags-for-binutils-2.38.patch
git am ../patch/loader-drop-argv-argument-in-grub_initrd_load.patch
git am ../patch/efi-add-definition-of-LoadFile2-protocol.patch
git am ../patch/efi-implemented-LoadFile2-initrd-loading-protocol-fo.patch
git am ../patch/linux-ignore-FDT-unless-we-need-to-modify-it.patch
git am ../patch/loader-Move-arm64-linux-loader-to-common-code.patch
git am ../patch/RISC-V-Update-image-header.patch
git am ../patch/RISC-V-Use-common-linux-loader.patch
git am ../patch/olpc-prefix-hack.patch
git am ../patch/core-in-fs.patch
git am ../patch/dpkg-version-comparison.patch
git am ../patch/grub-legacy-0-based-partitions.patch
git am ../patch/disable-floppies.patch
git am ../patch/grub.cfg-400.patch
git am ../patch/gfxpayload-keep-default.patch
git am ../patch/install-stage2-confusion.patch
git am ../patch/mkrescue-efi-modules.patch
git am ../patch/mkconfig-loopback.patch
git am ../patch/restore-mkdevicemap.patch
git am ../patch/gettext-quiet.patch
git am ../patch/install-efi-fallback.patch
git am ../patch/mkconfig-ubuntu-recovery.patch
git am ../patch/install-locale-langpack.patch
git am ../patch/mkconfig-nonexistent-loopback.patch
git am ../patch/no-insmod-on-sb.patch
git am ../patch/default-grub-d.patch
git am ../patch/blacklist-1440x900x32.patch
git am ../patch/mkconfig-ubuntu-distributor.patch
git am ../patch/ubuntu-linuxefi.patch
git am ../patch/mkconfig-signed-kernel.patch
git am ../patch/ubuntu-install-signed.patch
git am ../patch/wubi-no-windows.patch
git am ../patch/maybe-quiet.patch
git am ../patch/install-efi-adjust-distributor.patch
git am ../patch/quick-boot.patch
git am ../patch/quick-boot-lvm.patch
git am ../patch/gfxpayload-dynamic.patch
git am ../patch/vt-handoff.patch
git am ../patch/probe-fusionio.patch
git am ../patch/ignore-grub_func_test-failures.patch
git am ../patch/mkconfig-recovery-title.patch
git am ../patch/install-powerpc-machtypes.patch
git am ../patch/ieee1275-clear-reset.patch
git am ../patch/ppc64el-disable-vsx.patch
git am ../patch/grub-install-pvxen-paths.patch
git am ../patch/insmod-xzio-and-lzopio-on-xen.patch
git am ../patch/ubuntu-grub-install-extra-removable.patch
git am ../patch/mkconfig-other-inits.patch
git am ../patch/zpool-full-device-name.patch
git am ../patch/net-read-bracketed-ipv6-addr.patch
git am ../patch/bootp-new-net_bootp6-command.patch
git am ../patch/efinet-uefi-ipv6-pxe-support.patch
git am ../patch/bootp-process-dhcpack-http-boot.patch
git am ../patch/efinet-set-network-from-uefi-devpath.patch
git am ../patch/efinet-set-dns-from-uefi-proto.patch
git am ../patch/skip-grub_cmd_set_date.patch
git am ../patch/bash-completion-drop-have-checks.patch
git am ../patch/at_keyboard-module-init.patch
git am ../patch/uefi-secure-boot-cryptomount.patch
git am ../patch/efi-variable-storage-minimise-writes.patch
git am ../patch/dejavu-font-path.patch
git am ../patch/xen-no-xsm-policy-in-non-xsm-options.patch
git am ../patch/pc-verifiers-module.patch
git am ../patch/debug_verifiers.patch
git am ../patch/mkimage-fix-section-sizes.patch
git am ../patch/tpm-unknown-error-non-fatal.patch
git am ../patch/xfs-fix-v4-superblock.patch
git am ../patch/tests-ahci-update-qemu-device-name.patch
git am ../patch/minilzo-2.10.patch
git am ../patch/zstd-require-8-byte-buffer.patch
git am ../patch/ubuntu-zfs-enhance-support.patch
git am ../patch/ubuntu-zfs-gfxpayload-keep-default.patch
git am ../patch/ubuntu-zfs-mkconfig-ubuntu-recovery.patch
git am ../patch/ubuntu-zfs-mkconfig-ubuntu-distributor.patch
git am ../patch/ubuntu-zfs-mkconfig-signed-kernel.patch
git am ../patch/ubuntu-zfs-maybe-quiet.patch
git am ../patch/ubuntu-zfs-quick-boot.patch
git am ../patch/ubuntu-zfs-gfxpayload-dynamic.patch
git am ../patch/ubuntu-zfs-vt-handoff.patch
git am ../patch/ubuntu-zfs-mkconfig-recovery-title.patch
git am ../patch/ubuntu-zfs-insmod-xzio-and-lzopio-on-xen.patch
git am ../patch/ubuntu-support-initrd-less-boot.patch
git am ../patch/ubuntu-shorter-version-info.patch
git am ../patch/ubuntu-add-initrd-less-boot-fallback.patch
git am ../patch/ubuntu-mkconfig-leave-breadcrumbs.patch
git am ../patch/ubuntu-fix-lzma-decompressor-objcopy.patch
git am ../patch/ubuntu-temp-keep-auto-nvram.patch
git am ../patch/ubuntu-add-devicetree-command-support.patch
git am ../patch/ubuntu-boot-from-multipath-dependent-symlink.patch
git am ../patch/ubuntu-skip-disk-by-id-lvm-pvm-uuid-entries.patch
git am ../patch/ubuntu-efi-allow-loopmount-chainload.patch
git am ../patch/0076-ubuntu-Make-the-linux-command-in-EFI-grub-always-try.patch
git am ../patch/ubuntu-resilient-boot-ignore-alternative-esps.patch
git am ../patch/ubuntu-resilient-boot-boot-order.patch
git am ../patch/ubuntu-speed-zsys-history.patch
git am ../patch/ubuntu-flavour-order.patch
git am ../patch/ubuntu-dont-verify-loopback-images.patch
git am ../patch/ubuntu-recovery-dis_ucode_ldr.patch
git am ../patch/ubuntu-linuxefi-arm64.patch
git am ../patch/ubuntu-linuxefi-arm64-set-base-addr.patch
git am ../patch/ubuntu-add-initrd-less-boot-messages.patch
git am ../patch/ubuntu-fix-reproducible-squashfs-test.patch
git am ../patch/rhboot-f34-make-exit-take-a-return-code.patch
git am ../patch/rhboot-f34-dont-use-int-for-efi-status.patch
git am ../patch/rhboot-f34-make-pmtimer-tsc-calibration-fast.patch
git am ../patch/suse-grub.texi-add-net_bootp6-document.patch
git am ../patch/suse-add-support-for-UEFI-network-protocols.patch
git am ../patch/suse-AUDIT-0-http-boot-tracker-bug.patch
git am ../patch/rhboot-f34-efinet-also-use-the-firmware-acceleration-for-http.patch
git am ../patch/0241-Call-hwmatch-only-on-the-grub-pc-platform.patch
git am ../patch/cherrypick-efinet-correct-closing-snp-protocol.patch
git am ../patch/cherrypick-efi-grub_efi_close_protocol.patch
git am ../patch/no-devicetree-if-secure-boot.patch
git am ../patch/0077-ubuntu-Update-the-linux-boot-protocol-version-check.patch
git am ../patch/0096-linuxefi-fail-kernel-validation-without-shim-protoco.patch
git am ../patch/0099-chainloader-Avoid-a-double-free-when-validation-fail.patch
git am ../patch/0105-efilinux-Fix-integer-overflows-in-grub_cmd_initrd.patch
git am ../patch/ubuntu-verifiers-last.patch
git am ../patch/ubuntu-fuse3.patch
git am ../patch/ubuntu-os-prober-auto.patch
git am ../patch/efi-correct-struct-grub_efi_boot_services.patch
git am ../patch/efi-implement-grub_efi_run_image.patch
git am ../patch/fat-fix-listing-the-root-directory.patch
git am ../patch/efivar-check-that-efivarfs-is-writeable.patch
git am ../patch/linuxefi-do-not-validate-kernels-twice.patch
git am ../patch/fdt-add-debug-output-to-devicetree-command.patch
git am ../patch/efi-EFI-Device-Tree-Fixup-Protocol.patch
