#!/bin/bash

set -e

git am --abort || true
git checkout build
git reset --hard grub-2.06

git am ../patches/0001-loader-drop-argv-argument-in-grub_initrd_load.patch
git am ../patches/0002-efi-add-definition-of-LoadFile2-protocol.patch
git am ../patches/0003-efi-implemented-LoadFile2-initrd-loading-protocol-fo.patch
git am ../patches/0004-linux-ignore-FDT-unless-we-need-to-modify-it.patch
git am ../patches/0005-loader-Move-arm64-linux-loader-to-common-code.patch
git am ../patches/0006-RISC-V-Update-image-header.patch
git am ../patches/0007-RISC-V-Use-common-linux-loader.patch
git am ../patches/olpc-prefix-hack.patch
git am ../patches/core-in-fs.patch
git am ../patches/dpkg-version-comparison.patch
git am ../patches/grub-legacy-0-based-partitions.patch
git am ../patches/disable-floppies.patch
git am ../patches/grub.cfg-400.patch
git am ../patches/gfxpayload-keep-default.patch
git am ../patches/install-stage2-confusion.patch
git am ../patches/mkrescue-efi-modules.patch
git am ../patches/mkconfig-loopback.patch
git am ../patches/restore-mkdevicemap.patch
git am ../patches/gettext-quiet.patch
git am ../patches/install-efi-fallback.patch
git am ../patches/mkconfig-ubuntu-recovery.patch
git am ../patches/install-locale-langpack.patch
git am ../patches/mkconfig-nonexistent-loopback.patch
git am ../patches/no-insmod-on-sb.patch
git am ../patches/default-grub-d.patch
git am ../patches/blacklist-1440x900x32.patch
git am ../patches/mkconfig-ubuntu-distributor.patch
git am ../patches/ubuntu-linuxefi.patch
git am ../patches/mkconfig-signed-kernel.patch
git am ../patches/ubuntu-install-signed.patch
git am ../patches/wubi-no-windows.patch
git am ../patches/maybe-quiet.patch
git am ../patches/install-efi-adjust-distributor.patch
git am ../patches/quick-boot.patch
git am ../patches/quick-boot-lvm.patch
git am ../patches/gfxpayload-dynamic.patch
git am ../patches/vt-handoff.patch
git am ../patches/probe-fusionio.patch
git am ../patches/ignore-grub_func_test-failures.patch
git am ../patches/mkconfig-recovery-title.patch
git am ../patches/install-powerpc-machtypes.patch
git am ../patches/ieee1275-clear-reset.patch
git am ../patches/ppc64el-disable-vsx.patch
git am ../patches/grub-install-pvxen-paths.patch
git am ../patches/insmod-xzio-and-lzopio-on-xen.patch
git am ../patches/ubuntu-grub-install-extra-removable.patch
git am ../patches/mkconfig-other-inits.patch
git am ../patches/zpool-full-device-name.patch
git am ../patches/net-read-bracketed-ipv6-addr.patch
git am ../patches/bootp-new-net_bootp6-command.patch
git am ../patches/efinet-uefi-ipv6-pxe-support.patch
git am ../patches/bootp-process-dhcpack-http-boot.patch
git am ../patches/efinet-set-network-from-uefi-devpath.patch
git am ../patches/efinet-set-dns-from-uefi-proto.patch
git am ../patches/skip-grub_cmd_set_date.patch
git am ../patches/bash-completion-drop-have-checks.patch
git am ../patches/at_keyboard-module-init.patch
git am ../patches/uefi-secure-boot-cryptomount.patch
git am ../patches/efi-variable-storage-minimise-writes.patch
git am ../patches/dejavu-font-path.patch
git am ../patches/xen-no-xsm-policy-in-non-xsm-options.patch
git am ../patches/pc-verifiers-module.patch
git am ../patches/debug_verifiers.patch
git am ../patches/mkimage-fix-section-sizes.patch
git am ../patches/tpm-unknown-error-non-fatal.patch
git am ../patches/xfs-fix-v4-superblock.patch
git am ../patches/tests-ahci-update-qemu-device-name.patch
git am ../patches/minilzo-2.10.patch
git am ../patches/zstd-require-8-byte-buffer.patch
git am ../patches/ubuntu-zfs-enhance-support.patch
git am ../patches/ubuntu-zfs-gfxpayload-keep-default.patch
git am ../patches/ubuntu-zfs-mkconfig-ubuntu-recovery.patch
git am ../patches/ubuntu-zfs-mkconfig-ubuntu-distributor.patch
git am ../patches/ubuntu-zfs-mkconfig-signed-kernel.patch
git am ../patches/ubuntu-zfs-maybe-quiet.patch
git am ../patches/ubuntu-zfs-quick-boot.patch
git am ../patches/ubuntu-zfs-gfxpayload-dynamic.patch
git am ../patches/ubuntu-zfs-vt-handoff.patch
git am ../patches/ubuntu-zfs-mkconfig-recovery-title.patch
git am ../patches/ubuntu-zfs-insmod-xzio-and-lzopio-on-xen.patch
git am ../patches/ubuntu-support-initrd-less-boot.patch
git am ../patches/ubuntu-shorter-version-info.patch
git am ../patches/ubuntu-add-initrd-less-boot-fallback.patch
git am ../patches/ubuntu-mkconfig-leave-breadcrumbs.patch
git am ../patches/ubuntu-fix-lzma-decompressor-objcopy.patch
git am ../patches/ubuntu-temp-keep-auto-nvram.patch
git am ../patches/ubuntu-add-devicetree-command-support.patch
git am ../patches/ubuntu-boot-from-multipath-dependent-symlink.patch
git am ../patches/ubuntu-skip-disk-by-id-lvm-pvm-uuid-entries.patch
git am ../patches/ubuntu-efi-allow-loopmount-chainload.patch
git am ../patches/0076-ubuntu-Make-the-linux-command-in-EFI-grub-always-try.patch
git am ../patches/ubuntu-resilient-boot-ignore-alternative-esps.patch
git am ../patches/ubuntu-resilient-boot-boot-order.patch
git am ../patches/ubuntu-speed-zsys-history.patch
git am ../patches/ubuntu-flavour-order.patch
git am ../patches/ubuntu-dont-verify-loopback-images.patch
git am ../patches/ubuntu-recovery-dis_ucode_ldr.patch
git am ../patches/ubuntu-linuxefi-arm64.patch
git am ../patches/ubuntu-linuxefi-arm64-set-base-addr.patch
git am ../patches/ubuntu-add-initrd-less-boot-messages.patch
git am ../patches/ubuntu-fix-reproducible-squashfs-test.patch
git am ../patches/rhboot-f34-make-exit-take-a-return-code.patch
git am ../patches/rhboot-f34-dont-use-int-for-efi-status.patch
git am ../patches/rhboot-f34-make-pmtimer-tsc-calibration-fast.patch
git am ../patches/suse-grub.texi-add-net_bootp6-document.patch
git am ../patches/suse-add-support-for-UEFI-network-protocols.patch
git am ../patches/suse-AUDIT-0-http-boot-tracker-bug.patch
git am ../patches/rhboot-f34-efinet-also-use-the-firmware-acceleration-for-http.patch
git am ../patches/0241-Call-hwmatch-only-on-the-grub-pc-platform.patch
git am ../patches/cherrypick-efinet-correct-closing-snp-protocol.patch
git am ../patches/cherrypick-efi-grub_efi_close_protocol.patch
git am ../patches/no-devicetree-if-secure-boot.patch
git am ../patches/0077-ubuntu-Update-the-linux-boot-protocol-version-check.patch
git am ../patches/0096-linuxefi-fail-kernel-validation-without-shim-protoco.patch
git am ../patches/0099-chainloader-Avoid-a-double-free-when-validation-fail.patch
git am ../patches/0105-efilinux-Fix-integer-overflows-in-grub_cmd_initrd.patch
git am ../patches/ubuntu-verifiers-last.patch

git am ../patches/0001-efi-correct-struct-grub_efi_boot_services.patcht
git am ../patches/0001-fat-fix-listing-the-root-directory.patch
git am ../patches/0001-efi-implement-grub_efi_run_image.patch
